
const SERVICES=[
{name:'Facebook Auto Post',price:5000,icon:'send',desc:'Schedule branded Facebook content with a predictable draft → approval → publish workflow.'},
{name:'Facebook Comment Automation',price:2000,icon:'message-circle',desc:'Detect comments, answer common questions and route high-intent conversations.'},
{name:'Messenger Automation',price:5000,icon:'messages-square',desc:'Automate Messenger replies, qualification, lead capture and human handoff.'},
{name:'Automation Combo',price:9000,icon:'layers-3',desc:'A bundled Facebook + Instagram + Messenger implementation for connected workflows.'},
{name:'Instagram Automation',price:6000,icon:'camera',desc:'Automate publishing, comment responses and DM-oriented workflows.'},
{name:'WhatsApp Automation',price:4000,icon:'phone',desc:'Build structured WhatsApp Business response and lead-routing workflows.'},
{name:'YouTube Auto Upload',price:3000,icon:'play-circle',desc:'Prepare and automate video upload workflows with metadata and publishing steps.'},
{name:'AI Chatbot Development',price:null,icon:'bot',desc:'Custom AI-assisted support, qualification and lead capture experiences.'},
{name:'Business Workflow Automation',price:null,icon:'git-branch',desc:'Connect repetitive business steps into reliable trigger → decision → action systems.'},
{name:'CRM / Lead Automation',price:null,icon:'database',desc:'Capture, qualify and route leads into spreadsheets, CRMs or custom systems.'},
{name:'Vibe Coding',price:null,icon:'code-2',desc:'Rapid custom websites, dashboards and product interfaces from a clear product idea.'},
{name:'Custom Website / Web App',price:null,icon:'globe',desc:'Premium responsive websites and custom web applications built around your workflow.'}
];
let firebaseLive=false,auth=null,db=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function toast(msg,type='info'){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),3800)}
function setFirebaseStatus(label,ok=false){$$('[data-firebase-status]').forEach(x=>{x.innerHTML=`<span class=\"dot\"></span>${label}`;x.classList.toggle('bad',!ok)})}
function firebaseAuthError(err){const code=err?.code||'';if(code.includes('api-key-not-valid')||code==='auth/api-key-not-valid')return 'Firebase API key is invalid. Open Firebase Console → Project settings → Your apps → Web app, copy the current Web SDK config API key into firebase-config.js, then redeploy GitHub Pages.';return authMessage(err)}
function initFirebase(){
  try{
    const c=window.AUTOMATIQ_FIREBASE_CONFIG;
    if(!c||!window.firebase||!c.apiKey||c.apiKey.includes('YOUR_')){setFirebaseStatus('Firebase setup required');return;}
    if(!firebase.apps.length)firebase.initializeApp(c);
    auth=firebase.auth();db=firebase.firestore();firebaseLive=true;setFirebaseStatus('Checking Firebase…',true);
    auth.onAuthStateChanged(()=>setFirebaseStatus('Firebase Live',true),err=>{firebaseLive=false;setFirebaseStatus('Firebase Error');setAuthError(firebaseAuthError(err));});
  }catch(e){firebaseLive=false;auth=null;db=null;setFirebaseStatus('Firebase Error');console.warn(e);}
}

function nav(){const btn=$('#mobileToggle'),menu=$('#mobileMenu');if(btn&&menu)btn.onclick=()=>menu.classList.toggle('open');const path=location.pathname.split('/').pop()||'index.html';$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===path));updateAuthNav()}
function updateAuthNav(){if(!auth)return;auth.onAuthStateChanged(user=>{$$('[data-login]').forEach(a=>{a.textContent=user?'Dashboard':'Sign In';a.href=user?'dashboard.html':'login.html'});$$('[data-user-name]').forEach(x=>x.textContent=user?.displayName||user?.email?.split('@')[0]||'Workspace')})}
function boot(){const b=$('#boot');if(!b)return;const text=$('#bootText'),bar=$('#bootBar');let p=0;const states=['Initializing Automation Engine','Checking service map','Preparing workspace','System Ready'];const timer=setInterval(()=>{p+=8;if(bar)bar.style.width=Math.min(p,100)+'%';if(text)text.textContent=states[Math.min(Math.floor(p/25),3)];if(p>=100){clearInterval(timer);setTimeout(()=>b.classList.add('hide'),220)}},45);setTimeout(()=>b.classList.add('hide'),2500)}
function motion(){document.documentElement.classList.add('js-ready');if(matchMedia('(prefers-reduced-motion:reduce)').matches)document.documentElement.classList.add('reduced');if(window.IntersectionObserver){const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('show')),{threshold:.12});$$('.reveal').forEach(x=>io.observe(x))}else $$('.reveal').forEach(x=>x.classList.add('show'));const bar=$('#scrollBar');const update=()=>{if(bar){const h=document.documentElement.scrollHeight-innerHeight;bar.style.transform=`scaleX(${h?scrollY/h:0})`}};addEventListener('scroll',update,{passive:true});update()}
function icons(){if(window.lucide)lucide.createIcons()}
function heroSignals(){if(!$('#coreScene'))return;const scene=$('#coreScene');for(let i=1;i<=4;i++){const s=document.createElement('i');s.className=`signal s${i}`;scene.appendChild(s)}}
function workflow(){const steps=$$('.flowstep'),title=$('#stageTitle'),desc=$('#stageDesc'),log=$('#stageLog');if(!steps.length)return;let i=0;const data=[['Customer','A new customer starts a conversation.','Inbound event received'],['Message','The platform receives the message.','Message normalized'],['AI Detection','Intent and useful fields are identified.','Intent classified'],['AI Response','A response path is selected.','Response drafted'],['Automation','The workflow triggers the next action.','Action executed'],['Lead','Qualified information is captured.','Lead record prepared'],['CRM','The lead reaches the connected system.','CRM handoff ready']];const run=()=>{steps.forEach(x=>x.classList.remove('active'));const s=steps[i];if(s)s.classList.add('active');if(title)title.textContent=data[i][0];if(desc)desc.textContent=data[i][1];if(log)log.textContent=data[i][2];i=(i+1)%data.length};run();if(!matchMedia('(prefers-reduced-motion:reduce)').matches)setInterval(run,1600)}
function renderServices(){const host=$('#servicesGrid');if(!host)return;const groups=[['Social Automation',SERVICES.slice(0,7)],['AI & Business Systems',SERVICES.slice(7,10)],['Web & Product Development',SERVICES.slice(10)]];host.innerHTML=groups.map(([group,items])=>`<section class=\"service-group reveal\"><div class=\"sectionhead\"><span class=\"eyebrow\">${group}</span><h2>${group==='Social Automation'?'Turn conversations into repeatable actions.':group==='AI & Business Systems'?'Connect decisions, leads and business operations.':'Build the interface and product behind the workflow.'}</h2></div><div class=\"grid3\">${items.map(s=>`<article class=\"card hover service-card\"><div class=\"iconbox\"><i data-lucide=\"${s.icon}\"></i></div><div class=\"service-top\"><h3>${s.name}</h3>${s.price!==null?`<span class=\"service-price\">৳${s.price.toLocaleString('en-BD')}</span>`:'<span class=\"service-price custom\">Custom</span>'}</div><p>${s.desc}</p><div class=\"mini-flow\"><span>Trigger</span><b>→</b><span>Decision</span><b>→</b><span>Action</span></div><div class=\"service-actions\"><a class=\"btn secondary\" href=\"pricing.html?service=${encodeURIComponent(s.name)}\">${s.price!==null?'View package':'Request quote'} →</a><a class=\"btn ghost\" href=\"automation.html\">See flow</a></div></article>`).join('')}</div></section>`).join('');icons();motion();}

function renderPricing(){const host=$('#pricingGrid');if(!host)return;host.innerHTML=SERVICES.filter(s=>s.price!==null).map((s,i)=>`<article class=\"card price hover reveal ${i===3?'featured':''}\">${i===3?'<span class=\"price-badge\">Popular bundle</span>':''}<div><div class=\"iconbox\"><i data-lucide=\"${s.icon}\"></i></div><div class=\"service-top\"><h3>${s.name}</h3><span class=\"service-price\">৳${s.price.toLocaleString('en-BD')}</span></div><p>${s.desc}</p><ul><li>Implementation planning</li><li>Workflow setup & testing</li><li>Handoff documentation</li><li>Client support path</li></ul></div><button class=\"btn ${i===3?'primary':'secondary'}\" data-order=\"${s.name}\">Request this service →</button></article>`).join('');icons();$$('[data-order]').forEach(b=>b.onclick=()=>openOrder(b.dataset.order));const wanted=new URLSearchParams(location.search).get('service');if(wanted){setTimeout(()=>{const btn=$$('[data-order]').find(x=>x.dataset.order===wanted);btn?.scrollIntoView({behavior:'smooth',block:'center'});btn?.focus()},150)}}

function openOrder(service){if(!firebaseLive||!auth){location.href=`login.html?return=pricing.html&service=${encodeURIComponent(service)}`;return}if(auth.currentUser){$('#orderService').value=service;$('#orderModal').classList.add('open');return}const stop=auth.onAuthStateChanged(u=>{stop();if(!u){location.href=`login.html?return=pricing.html&service=${encodeURIComponent(service)}`;return}$('#orderService').value=service;$('#orderModal').classList.add('open')},err=>{stop();setAuthError(firebaseAuthError(err))})}
async function submitOrder(e){e.preventDefault();const f=e.currentTarget;const service=$('#orderService').value;const business=$('#orderBusiness').value.trim();const req=$('#orderRequirements').value.trim();if(!business||!req)return;if(!firebaseLive||!auth?.currentUser){toast('Please sign in before submitting an order.','error');return}try{await db.collection('orders').add({userId:auth.currentUser.uid,serviceName:service,businessName:business,requirements:req,status:'pending',createdAt:firebase.firestore.FieldValue.serverTimestamp()});$('#orderModal').classList.remove('open');f.reset();toast('Service request submitted. You can track it from your dashboard.','success')}catch(err){toast('Could not submit the request. Check your Firebase/Firestore setup.','error');console.error(err)}}
function authPage(){
 const lf=$('#loginForm'),sf=$('#signupForm');
 if(!lf&&!sf)return;
 const show=(signup)=>{
   $('#loginTab')?.classList.toggle('active',!signup);$('#signupTab')?.classList.toggle('active',signup);
   if(lf)lf.style.display=signup?'none':'block';if(sf)sf.style.display=signup?'block':'none';
   if($('#authTitle'))$('#authTitle').textContent=signup?'Create your workspace':'Welcome back';
   if($('#authSub'))$('#authSub').textContent=signup?'Set up your Automatiq client account.':'Sign in to your Automatiq client workspace.';
 };
 $('#loginTab')?.addEventListener('click',()=>show(false));$('#signupTab')?.addEventListener('click',()=>show(true));
 if(!firebaseLive){setAuthError('Firebase is not ready. Check the Firebase Web API key in firebase-config.js.');return;}
 auth.onAuthStateChanged(u=>{if(u&&location.pathname.endsWith('login.html')&&!new URLSearchParams(location.search).get('force'))location.href='dashboard.html';},err=>{firebaseLive=false;setAuthError(firebaseAuthError(err));});
 lf?.addEventListener('submit',async e=>{e.preventDefault();if(!firebaseLive||!auth)return setAuthError('Firebase authentication is unavailable. Please fix the Firebase configuration first.');try{await auth.signInWithEmailAndPassword($('#email').value.trim(),$('#password').value);location.href=new URLSearchParams(location.search).get('return')||'dashboard.html'}catch(err){setAuthError(firebaseAuthError(err))}});
 sf?.addEventListener('submit',async e=>{e.preventDefault();if(!firebaseLive||!auth)return setAuthError('Firebase authentication is unavailable. Please fix the Firebase configuration first.');const name=$('#signupName').value.trim(),email=$('#signupEmail').value.trim(),pass=$('#signupPassword').value;if(pass.length<6)return setAuthError('Password must contain at least 6 characters.');try{const c=await auth.createUserWithEmailAndPassword(email,pass);await c.user.updateProfile({displayName:name});await db.collection('users').doc(c.user.uid).set({uid:c.user.uid,name,email,createdAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});location.href='dashboard.html'}catch(err){setAuthError(firebaseAuthError(err))}});
 $('#resetPassword')?.addEventListener('click',async()=>{const email=$('#email').value.trim();if(!email)return setAuthError('Enter your email first.');if(!firebaseLive||!auth)return setAuthError('Firebase authentication is unavailable.');try{await auth.sendPasswordResetEmail(email);toast('Password reset email sent. Check your inbox.','success')}catch(err){setAuthError(firebaseAuthError(err))}});
 show(new URLSearchParams(location.search).get('mode')==='signup');
}

function authMessage(e){const m={'auth/invalid-credential':'Email or password is incorrect.','auth/user-not-found':'No account was found with this email.','auth/wrong-password':'Email or password is incorrect.','auth/email-already-in-use':'An account already exists with this email.','auth/weak-password':'Use a stronger password.','auth/invalid-email':'Please enter a valid email address.','auth/operation-not-allowed':'Email/password sign-in is disabled in Firebase Authentication.','auth/network-request-failed':'Network error. Check your connection and try again.','auth/too-many-requests':'Too many attempts. Wait a moment and try again.'};return m[e?.code]||e?.message||'Authentication failed.'}function setAuthError(m){const x=$('#authError');if(x){x.textContent=m;x.classList.add('visible')}else toast(m,'error')}
async function dashboard(){if(!$('#dashboardApp')||!auth)return;auth.onAuthStateChanged(async user=>{if(!user){location.href='login.html?return=dashboard.html';return}$('#dashName').textContent=user.displayName||user.email.split('@')[0];$('#dashEmail').textContent=user.email;try{const snap=await db.collection('orders').where('userId','==',user.uid).limit(50).get();const orders=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>{const ta=a.createdAt?.toMillis?a.createdAt.toMillis():0;const tb=b.createdAt?.toMillis?b.createdAt.toMillis():0;return tb-ta}).slice(0,20);renderOrders(orders);$('#orderCount').textContent=orders.filter(o=>o.status!=='completed').length.toString().padStart(2,'0');$('#serviceCount').textContent=new Set(orders.map(o=>o.serviceName)).size.toString().padStart(2,'0')}catch(e){renderOrders([]);toast('Orders could not be loaded. Check Firestore rules/indexes.','error')}} ,err=>{firebaseLive=false;toast(firebaseAuthError(err),'error')});$('#logout')?.addEventListener('click',async()=>{await auth.signOut();location.href='index.html'});$('#requestConnection')?.addEventListener('click',()=>toast('Connection requests should be submitted with the platform, page/account and required permission details.','info'))}
function renderOrders(orders){const host=$('#ordersBody');if(!host)return;if(!orders.length){host.innerHTML='<tr><td colspan="4">No service requests yet. Start from the Pricing page.</td></tr>';return}host.innerHTML=orders.map(o=>`<tr><td>${escapeHtml(o.serviceName||'Service')}</td><td>${escapeHtml(o.businessName||'—')}</td><td><span class="pill ${o.status==='completed'?'good':o.status==='pending'?'warn':'neutral'}">${escapeHtml(o.status||'pending')}</span></td><td>${o.createdAt?.toDate?o.createdAt.toDate().toLocaleDateString(): 'Recently'}</td></tr>`).join('')}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
const KB=[[/price|pricing|cost|package|৳/i,'Current public packages: Facebook Auto Post ৳5,000; Facebook Comment Automation ৳2,000; Messenger Automation ৳5,000; Automation Combo ৳9,000; Instagram Automation ৳6,000; WhatsApp Automation ৳4,000; YouTube Auto Upload ৳3,000. Custom AI, workflow, CRM, Vibe Coding and web-app projects are quoted separately.'],[/facebook.*comment|comment.*facebook/i,'Facebook Comment Automation can classify comments, generate structured replies and route high-intent conversations into a lead workflow.'],[/messenger/i,'Messenger Automation handles structured replies, qualification, lead capture and human handoff.'],[/instagram|dm/i,'Instagram Automation can cover publishing, comment responses and DM workflows when the required Meta permissions are configured.'],[/whatsapp/i,'WhatsApp Automation depends on WhatsApp Business/API access and approved permissions/templates where required.'],[/crm|lead/i,'CRM / Lead Automation captures customer information, qualifies it and routes it into supported CRM or spreadsheet systems.'],[/website|web app|vibe|coding/i,'Automatiq can build responsive websites, dashboards and custom web applications around a defined workflow.'],[/login|sign in|signup|account/i,'Use the Login / Signup page to create or access a Firebase-backed client account.'],[/support|ticket|help|problem|bug/i,'Describe the page, the expected behavior and what happened. For account-specific issues, sign in and submit a support request from your workspace.']];
function answer(q){for(const [r,a] of KB)if(r.test(q))return a;return 'I can explain Automatiq services, pricing, workflows, login, CRM/lead automation and support. Tell me what you want to automate and I will point you to the right section.'}
function chat(){const box=$('#messages'),form=$('#chatForm'),input=$('#chatInput');if(!box||!form)return;const add=(txt,who)=>{const d=document.createElement('div');d.className=`bubble ${who}`;d.textContent=txt;box.appendChild(d);box.scrollTop=box.scrollHeight};add('Hi! I can help with Automatiq services, pricing, workflow setup and client support.','ai');$$('[data-prompt]').forEach(b=>b.onclick=()=>{input.value=b.dataset.prompt;form.requestSubmit()});form.onsubmit=e=>{e.preventDefault();const q=input.value.trim();if(!q)return;add(q,'user');input.value='';setTimeout(()=>add(answer(q),'ai'),320)}}
async function ticketForm(){const form=$('#ticketForm');if(!form||!auth)return;form.addEventListener('submit',async e=>{e.preventDefault();const u=auth.currentUser;if(!u){toast('Please sign in to submit a support ticket.','error');return}try{await db.collection('supportTickets').add({userId:u.uid,subject:$('#ticketSubject').value.trim(),message:$('#ticketMessage').value.trim(),status:'open',createdAt:firebase.firestore.FieldValue.serverTimestamp()});form.reset();toast('Support ticket submitted.','success')}catch(err){toast('Ticket could not be submitted. Check Firestore rules.','error')}})}
function closeModals(){document.addEventListener('click',e=>{if(e.target.matches('[data-close-modal]')||e.target.classList.contains('modal-backdrop'))e.target.closest('.modal-backdrop')?.classList.remove('open')})}
function init(){initFirebase();nav();motion();boot();heroSignals();workflow();renderServices();renderPricing();authPage();dashboard();chat();ticketForm();closeModals();icons();$('#orderForm')?.addEventListener('submit',submitOrder)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
